redis:
  host: redis-11660.re-cluster1.ps-redislabs.org
  port: 11660
  username: ""
  password: ""
  timeout: 5000

rest-api:
  host: https://re-cluster1.ps-redislabs.org
  port: 9443
  username: admin@rl.org
  password: FEwNu3a

unified-jedis:
  host: redis-12191.re-cluster1.ps-redislabs.org
  port: 12191
  username: ""
  password: ""
